[default]
src = 'contracts'
out = 'artifacts_forge'
remappings = [
  'ds-test/=lib/ds-test/src/', 
  'forge-std/=lib/forge-std/src/', 
  '@openzeppelin/contracts-upgradeable/=lib/openzeppelin-contracts-upgradeable/contracts',
  '@rari-capital/solmate=lib/solmate'
]
auto_detect_solc = true

# See more config options https://github.com/gakonst/foundry/tree/master/config