name: Working Repo

on:
  push:
    branches:
      - main
      - development
      - feat/publish-**
  pull_request:
    branches: [main, development]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
          cache: "npm"
      - run: npm install
      - uses: JS-DevTools/npm-publish@v1.4.3
        with:
          token: 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
          registry: https://npm.pkg.github.com
          tag: ${{env.GITHUB_REF_NAME == 'feat/public-package' && 'beta'}}
          dry-run: true
